### ISSUE TITLE
Healthchecks are always unhealthy

### ISSUE THREAD

**Issue by 1337-server** [Organizr/docker-base#8]
It seems that the health checks on the container always return unhealthy. 
This looks to be because the port mapping is mapped to port 8080 on the healthcheck, however the port that the container uses is port 80.

I tried to fix this in my own fork, and it worked in that it no longer returns a `refused connection` but a `404 error`, but when I checked the health check ping locations it does seem as though the container is not creating these pages
`http://$(hostname -i):80/nginx_status` 
`http://$(hostname -i):80/php_status`

It seems that nginx is either ignoring the config file (`/root/defaults/healthcheck`) or something else is blocking these pages from correctly being configured.

**Comment by Roxedus** [comment]
Cannot reproduce. `docker run -it -p 80:80 --name test ghcr.io/organizr/base:2022-05-27_20` comes up as healthy

**Comment by 1337-server** [comment]
Was using an old image tag.
