### ISSUE TITLE
Move cloned repository outside /config volume

### ISSUE THREAD

**Issue by xsolinsx** [Organizr/docker-base#9]
Hello, is it necessary to have the cloned repository inside the /config volume?

I'm asking this because I have a script backing up my volumes and I find it pretty pointless to have the files of the repository inside the volume, in my opinion those files would be better located inside the container and not on the /config volume.

For example PiHole also needs a volume for configurations but that volume only contains config files, not the whole git repository (which is found inside the container at /var/www/html/admin)

Thanks

**Comment by Roxedus** [comment]
With the current setup in Organizr in how persistent storage is stored, it is the safest bet, I do wish it wasn't the case however.

It has gotten a lot better within the last year, so it might be worth revisiting.
